sonar.organization=jlvenero
sonar.projectKey=jlvenero_thrivecorp
sonar.projectName=ThriveCorp

sonar.sources=backend,frontend/src

sonar.exclusions=**/*.test.js,**/*.test.jsx,**/node_modules/**,**/dist/**,**/*.config.js,**/jest.config.js,**/vite.config.js,**/*.test.js,**/.ebextensions/**, **/coverage/**, frontend/src/pages/AdminBillingReport/**/*, frontend/src/pages/AdminDashboard.jsx

sonar.coverage.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js,backend/server.js,backend/routes/**,backend/jest.config.js,backend/utils/metrics.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git